name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Prepare certificate and properties files
        run: |
          echo "prepare step"
          pwd
          ls
          mkdir -p $HOME/.azure
          if [-d $HOME/.azure ]; then
            echo "Directory $HOME/.azure exists"
          else
            echo "Directory $HOME/.azure does not exists"
          fi
          
          if [[ -f "ojdbc-provider-azure/test.properties" ]]; then
            echo "File azure/test.properties exists."
          else
            echo "File azure/test.properties does not exist."
          fi
          
          # Generate certificate
          echo "${{ secrets.TEST_AZURE_CERTIFICATE }}" > $HOME/.azure/ojdbc-plugin-test-app.pem

          if [[ -f "$HOME/.azure/ojdbc-plugin-test-app.pem" ]]; then
            echo "File .azure/.pem exists."
          else
            echo "File .azure/.pem does not exist."
          fi

          # Convert .pem to .pfx file
          openssl pkcs12 -export -in ${{ secrets.TEST_AZURE_CLIENT_CERTIFICATE_PATH }} -passout pass:${{ secrets.TEST_AZURE_CLIENT_PFX_PASSWORD }} -out ojdbc-provider-azure/ojdbc-provider-test-app.pfx

          if [[ -f "ojdbc-provider-azure/ojdbc-provider-test-app.pfx" ]]; then
            echo "File azure/.pfx exists."
          else
            echo "File azure/.pfx does not exist."
          fi
          
          # Generate ojdbc-provider-azure/test.properties
          echo -e "OCI_CONFIG_FILE=${{ secrets.TEST_OCI_CONFIG_FILE }}\n" >> ojdbc-provider-oci/test.properties
          echo -e "AZURE_MANAGED_IDENTITY=false\n
          AZURE_TENANT_ID=${{ secrets.TEST_AZURE_TENANT_ID }}\n
          AZURE_CLIENT_ID=${{ secrets.TEST_AZURE_CLIENT_ID }}\n
          AZURE_CLIENT_SECRET=${{ secrets.TEST_AZURE_CLIENT_SECRET }}\n
          AZURE_CLIENT_CERTIFICATE_PATH=${{ secrets.TEST_AZURE_CLIENT_CERTIFICATE_PATH }}\n
          AZURE_CLIENT_PFX_CERTIFICATE_PATH=./ojdbc-provider-test-app.pfx\n
          AZURE_CLIENT_PFX_PASSWORD=${{ secrets.TEST_AZURE_CLIENT_PFX_PASSWORD }}\n
          AZURE_TOKEN_SCOPE=${{ secrets.TEST_AZURE_TOKEN_SCOPE }}\n
          AZURE_APP_CONFIG_NAME=${{ secrets.TEST_AZURE_APP_CONFIG_NAME }}\n
          AZURE_APP_CONFIG_KEY=${{ secrets.TEST_AZURE_APP_CONFIG_KEY }}\n
          AZURE_APP_CONFIG_LABEL=${{ secrets.TEST_AZURE_APP_CONFIG_LABEL }}\n
          AZURE_KEY_VAULT_URL=${{ secrets.TEST_AZURE_KEY_VAULT_URL }}\n
          AZURE_KEY_VAULT_SECRET_NAME=${{ secrets.TEST_AZURE_KEY_VAULT_SECRET_NAME }}\n
          " >> ojdbc-provider-azure/test.properties

          if [[ -f "ojdbc-provider-azure/test.properties" ]]; then
            echo "File azure/test.properties exists."
          else
            echo "File azure/test.properties does not exist."
          fi
          
      - name: Run tests with Maven
        run: |
          echo "run tests step"
          mvn -B test --file pom.xml
      - name: Clean up
        run: |
          rm $HOME/.azure/ojdbc-plugin-test-app.pem
          rm ojdbc-provider-azure/ojdbc-provider-test-app.pfx

          rm ojdbc-provider-azure/test.properties

