name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Prepare certificate and properties files
        run: |
          echo "prepare step"
          pwd
          ls
          mkdir -p ~/.oci
          mkdir -p ~/.azure
          
          cat "${{ secrets.TEST_AZURE_CERTIFICATE }}" > ~/.azure/ojdbc-plugin-test-app.pem
          openssl pkcs12 -export -in ${{ secrets.TEST_AZURE_CLIENT_CERTIFICATE_PATH }} -passout pass:${{ secrets.TEST_AZURE_CLIENT_PFX_PASSWORD }} -out ojdbc-provider-azure/ojdbc-provider-test-app.pfx
          
          echo -e "OCI_CONFIG_FILE=${{ secrets.TEST_OCI_CONFIG_FILE }}\n" >> ojdbc-provider-oci/test.properties
          echo -e "AZURE_MANAGED_IDENTITY=false\n
          AZURE_CLIENT_PFX_CERTIFICATE_PATH=./ojdbc-provider-test-app.pfx\n" >> ojdbc-provider-azure/test.properties
          
      - name: Run tests with Maven
        run: |
          echo "run tests step"
          mvn -B test --file pom.xml

